// Add a new entry here whenever a new post is published.
// blog.html reads this list, sorts by date (newest first),
// and automatically paginates it 6 posts per page.
const BLOG_POSTS = [
  {
    slug: "building-neon-dodge",
    title: "Building Neon Dodge: Why Starting Simple Was the Right Call",
    category: "Dev Blog",
    date: "2026-06-17",
    dateLabel: "Jun 17, 2026",
    summary: "Neon Dodge was supposed to be a quick prototype. Three days later I was still tuning collision detection — and realizing why starting small is never a concession.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #2bd1c4, #1f4f4c)",
    thumb: "/assets/thumbs/neon-dodge.png",
  },
  {
    slug: "zombie-survival-arena-design",
    title: "Zombie Survival and What I Learned About Arena Design",
    category: "Dev Blog",
    date: "2026-06-16",
    dateLabel: "Jun 16, 2026",
    summary: "Building an arena where zombies chase you from all sides taught me that the real challenge isn't the enemies — it's the space between them.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #73d676, #1a4a1c)",
    thumb: "/assets/thumbs/zombie-survival.png",
  },
  {
    slug: "keyboard-vs-touch-getting-the-best-score",
    title: "Keyboard vs. Touch: Getting the Best Score",
    category: "Guide",
    date: "2026-06-15",
    dateLabel: "Jun 15, 2026",
    summary: "Every game on Webgame Arcades supports both keyboard and touch controls. We break down which input works best for which game genre.",
    thumbLabel: "TIP",
    thumbGradient: "linear-gradient(135deg, #2bd1c4, #1f8f86)",
  },
  {
    slug: "space-shooter-auto-fire",
    title: "Space Shooter: Why I Let the Ship Fire Itself",
    category: "Dev Blog",
    date: "2026-06-15",
    dateLabel: "Jun 15, 2026",
    summary: "Removing the fire button from a shoot-em-up sounds wrong. But auto-fire shifted all the skill into movement — and that turned out to be the better game.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #a98bff, #3a2a7a)",
    thumb: "/assets/thumbs/space-shooter.png",
  },
  {
    slug: "building-ninja-dash",
    title: "Building Ninja Dash: The Problem With Endless Runners",
    category: "Dev Blog",
    date: "2026-06-14",
    dateLabel: "Jun 14, 2026",
    summary: "Every endless runner faces the same question: how do you keep the loop interesting past the first 30 seconds? Here's how I tried to solve it.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #f4f2ea, #3a3a4a)",
    thumb: "/assets/thumbs/ninja-dash.png",
  },
  {
    slug: "building-robot-arena",
    title: "Robot Arena: Chasing Bots and Collision Headaches",
    category: "Dev Blog",
    date: "2026-06-13",
    dateLabel: "Jun 13, 2026",
    summary: "Getting multiple bots to chase the player without clustering into a useless blob took more iteration than I expected. Here's what finally worked.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #2bd1c4, #4b4f9c)",
    thumb: "/assets/thumbs/robot-arena.png",
  },
  {
    slug: "building-arrow-dodge",
    title: "Arrow Dodge: Building a Pure Reaction Speed Test",
    category: "Dev Blog",
    date: "2026-06-12",
    dateLabel: "Jun 12, 2026",
    summary: "I wanted to build something that measured pure reaction time with no strategy layer. Stripping a game down to just one skill is harder than it sounds.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #f7b84b, #8a4a00)",
    thumb: "/assets/thumbs/arrow-dodge.png",
  },
  {
    slug: "building-monster-punch",
    title: "Monster Punch: Reinventing Whack-a-Mole for the Browser",
    category: "Dev Blog",
    date: "2026-06-11",
    dateLabel: "Jun 11, 2026",
    summary: "Whack-a-mole is one of those games everyone knows but nobody has bothered to get right in a browser. Here's what I changed and why.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #f05d5e, #6a1a1b)",
    thumb: "/assets/thumbs/monster-punch.png",
  },
  {
    slug: "6-new-games-added-to-the-arcade",
    title: "6 New Games Added to the Arcade",
    category: "Release",
    date: "2026-06-10",
    dateLabel: "Jun 10, 2026",
    summary: "We just shipped six new browser games, from reflex testers to puzzle challenges. Here's a quick look at what's new and how to play each one.",
    thumbLabel: "NEW",
    thumbGradient: "linear-gradient(135deg, #f7b84b, #e85d4c)",
  },
  {
    slug: "building-car-smash",
    title: "Car Smash: When Destruction Is the Entire Game",
    category: "Dev Blog",
    date: "2026-06-10",
    dateLabel: "Jun 10, 2026",
    summary: "Most games reward survival. Car Smash rewards total obliteration. Designing a game where the only goal is to destroy something completely changed how I thought about progression.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #f05d5e, #f7b84b)",
    thumb: "/assets/thumbs/car-smash.png",
  },
  {
    slug: "building-laser-escape",
    title: "Laser Escape: The Surprisingly Hard Part Was the Lasers",
    category: "Dev Blog",
    date: "2026-06-09",
    dateLabel: "Jun 9, 2026",
    summary: "Moving laser walls sound simple. But getting the timing, gaps, and hitboxes to feel fair without feeling easy took far longer than building the rest of the game.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #f05d5e, #2a0a0a)",
    thumb: "/assets/thumbs/laser-escape.png",
  },
  {
    slug: "building-castle-defender",
    title: "Castle Defender: Building a One-Button Tower Defense",
    category: "Dev Blog",
    date: "2026-06-08",
    dateLabel: "Jun 8, 2026",
    summary: "Tower defense games usually drown you in menus and resource management. I wanted to strip it down to just aiming and shooting. Here's what that process looked like.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #f7b84b, #4a3000)",
    thumb: "/assets/thumbs/castle-defender.png",
  },
  {
    slug: "building-bomb-runner",
    title: "Bomb Runner: Obstacles, Jump Timing, and the Rhythm Problem",
    category: "Dev Blog",
    date: "2026-06-07",
    dateLabel: "Jun 7, 2026",
    summary: "Endless runners live or die by their obstacle rhythm. I spent more time on the spacing algorithm than on anything else in this game.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #f05d5e, #f7b84b)",
    thumb: "/assets/thumbs/bomb-runner.png",
  },
  {
    slug: "building-meteor-dodge",
    title: "Meteor Dodge: Making the Same Idea Feel Different",
    category: "Dev Blog",
    date: "2026-06-06",
    dateLabel: "Jun 6, 2026",
    summary: "Dodge-the-falling-things is one of the oldest game loops. Making it feel fresh required rethinking almost every variable: size, speed, density, and momentum.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #a98bff, #1a0a3a)",
    thumb: "/assets/thumbs/meteor-dodge.png",
  },
  {
    slug: "building-pop-blitz",
    title: "Pop Blitz: Designing a Game Where the Clock Is the Enemy",
    category: "Dev Blog",
    date: "2026-06-05",
    dateLabel: "Jun 5, 2026",
    summary: "Most tapping games count down from a single timer. Pop Blitz gives every shape its own clock. That one change made the game feel completely different.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #2bd1c4, #f7b84b)",
    thumb: "/assets/thumbs/pop-blitz.png",
  },
  {
    slug: "building-water-balloon-blitz",
    title: "Water Balloon Blitz: Adding a Penalty Changed Everything",
    category: "Dev Blog",
    date: "2026-06-04",
    dateLabel: "Jun 4, 2026",
    summary: "The game was fine before I added the bomb balloon penalty. Then I added it and suddenly every tap became a real decision. That's when it got interesting.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #2bd1c4, #1a4faa)",
    thumb: "/assets/thumbs/water-balloon-blitz.png",
  },
  {
    slug: "building-time-stop",
    title: "Time Stop: The Simplest Idea That Took the Longest to Get Right",
    category: "Dev Blog",
    date: "2026-06-03",
    dateLabel: "Jun 3, 2026",
    summary: "Press a button to stop the timer at exactly the right moment. That's the whole game. Making something this minimal feel satisfying was harder than any complex mechanic I've built.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #a98bff, #2bd1c4)",
    thumb: "/assets/thumbs/time-stop.png",
  },
  {
    slug: "building-memory-grid",
    title: "Memory Grid: What Building a Memory Game Taught Me",
    category: "Dev Blog",
    date: "2026-06-02",
    dateLabel: "Jun 2, 2026",
    summary: "I thought a memory game would be one of the simpler builds. The display timing, grid size, and recall model turned it into one of the most carefully tuned games on the site.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #a98bff, #4b1a8a)",
    thumb: "/assets/thumbs/memory-grid.png",
  },
  {
    slug: "building-lane-rush",
    title: "Lane Rush: Why Three Lanes Is the Magic Number",
    category: "Dev Blog",
    date: "2026-06-01",
    dateLabel: "Jun 1, 2026",
    summary: "Two lanes is too binary. Four lanes creates dead zones. Three lanes keeps every switch meaningful. Getting there took more failed versions than I expected.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #f7b84b, #2bd1c4)",
    thumb: "/assets/thumbs/lane-rush.png",
  },
  {
    slug: "building-paint-race",
    title: "Paint Race: When I Added a Computer Opponent, Everything Changed",
    category: "Dev Blog",
    date: "2026-05-31",
    dateLabel: "May 31, 2026",
    summary: "The first version of Paint Race was just painting a canvas. It was fine. Adding an AI opponent with intentional imperfection turned it into a game.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #2bd1c4, #f05d5e)",
    thumb: "/assets/thumbs/paint-race.png",
  },
  {
    slug: "building-tap-sprint",
    title: "Tap Sprint: Making Speed Feel Physical in a Browser Game",
    category: "Dev Blog",
    date: "2026-05-30",
    dateLabel: "May 30, 2026",
    summary: "Tap as fast as you can to run faster than your opponents. Translating physical effort into game speed without frustrating the player took a lot of iteration.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #73d676, #1a6a1c)",
    thumb: "/assets/thumbs/tap-sprint.png",
  },
  {
    slug: "building-pendulum-hit",
    title: "Pendulum Hit: When the Entire Game Is a Single Moment",
    category: "Dev Blog",
    date: "2026-05-29",
    dateLabel: "May 29, 2026",
    summary: "The whole game is one tap at the right time. Everything else — the arc, the timing window, the 10-stage difficulty curve — exists to make that moment feel earned.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #f7b84b, #a98bff)",
    thumb: "/assets/thumbs/pendulum-hit.png",
  },
  {
    slug: "building-block-stacker",
    title: "Block Stacker: What I Learned Rebuilding a Classic",
    category: "Dev Blog",
    date: "2026-05-28",
    dateLabel: "May 28, 2026",
    summary: "Everyone knows Tetris. Building your own version from scratch reveals just how much invisible craft went into the original — especially the rotation system.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #2bd1c4, #a98bff)",
    thumb: "/assets/thumbs/block-stacker.png",
  },
  {
    slug: "building-tile-link",
    title: "Tile Link: The Path-Finding Problem I Did Not Expect",
    category: "Dev Blog",
    date: "2026-05-27",
    dateLabel: "May 27, 2026",
    summary: "Connecting two matching tiles sounds trivial. Implementing the two-bend path sweep algorithm correctly, and generating solvable boards, was anything but.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #f05d5e, #a98bff)",
    thumb: "/assets/thumbs/tile-link.png",
  },
  {
    slug: "building-crate-shift",
    title: "Crate Shift: Why Sokoban Is Harder to Build Than It Looks",
    category: "Dev Blog",
    date: "2026-05-26",
    dateLabel: "May 26, 2026",
    summary: "Sokoban is 40 years old and still one of the trickiest puzzles to implement correctly. Collision edge cases and deadlock detection kept me busy for days.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #f7b84b, #73d676)",
    thumb: "/assets/thumbs/crate-shift.png",
  },
  {
    slug: "building-marble-gate",
    title: "Marble Gate: Designing a Sliding Puzzle That Feels Fair",
    category: "Dev Blog",
    date: "2026-05-25",
    dateLabel: "May 25, 2026",
    summary: "Sliding block puzzles can feel arbitrary and frustrating. Getting Marble Gate to feel logical — where every solution is discoverable — meant designing backwards from the answer.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #2bd1c4, #73d676)",
    thumb: "/assets/thumbs/marble-gate.png",
  },
  {
    slug: "building-maze-escape",
    title: "Maze Escape: The Joy and Pain of Procedural Generation",
    category: "Dev Blog",
    date: "2026-05-24",
    dateLabel: "May 24, 2026",
    summary: "Every run of Maze Escape generates a new maze. Getting the generation algorithm right — and making every maze actually fun to navigate — took more thinking than I expected.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #73d676, #2bd1c4)",
    thumb: "/assets/thumbs/maze-escape.png",
  },
  {
    slug: "building-shelf-snap",
    title: "Shelf Snap: A Game About Keeping Things From Falling Apart",
    category: "Dev Blog",
    date: "2026-05-23",
    dateLabel: "May 23, 2026",
    summary: "Books sliding off a shelf sounds absurd. But the frantic energy of watching things escape your control — and snapping them back just in time — turned out to be genuinely satisfying.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #f7b84b, #a98bff)",
    thumb: "/assets/thumbs/shelf-snap.png",
  },
  {
    slug: "building-otter-pop",
    title: "Otter Pop: Why Adding a Personality Changed the Whole Feel",
    category: "Dev Blog",
    date: "2026-05-22",
    dateLabel: "May 22, 2026",
    summary: "The mechanic was already working before I added the otters. The moment I gave the targets a personality with idle animations and reactions, it became a different game.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #73d676, #f7b84b)",
    thumb: "/assets/thumbs/otter-pop.png",
  },
  {
    slug: "building-sudoku",
    title: "Building Sudoku: A Classic Puzzle in 200 Lines",
    category: "Dev Blog",
    date: "2026-05-21",
    dateLabel: "May 21, 2026",
    summary: "Setting a 200-line limit forced me to cut every non-essential feature. The constraint produced a cleaner puzzle experience than I would have shipped without it.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #a98bff, #2bd1c4)",
    thumb: "/assets/thumbs/sudoku.png",
  },
  {
    slug: "building-trap-scout",
    title: "Trap Scout: Rebuilding Minesweeper Without the Frustration",
    category: "Dev Blog",
    date: "2026-05-20",
    dateLabel: "May 20, 2026",
    summary: "Classic Minesweeper has a first-click death problem and unavoidable 50/50 guesses. I tried to build a version where every loss is actually your fault.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #f05d5e, #73d676)",
    thumb: "/assets/thumbs/trap-scout.png",
  },
  {
    slug: "building-window-wash",
    title: "Window Wash: When the Strangest Idea Turned Out to Be Fun",
    category: "Dev Blog",
    date: "2026-05-19",
    dateLabel: "May 19, 2026",
    summary: "I almost cut Window Wash from the list because the concept seemed too strange. The canvas-reveal mechanic turned out to be one of the most satisfying things I've built.",
    thumbLabel: "DEV",
    thumbGradient: "linear-gradient(135deg, #2bd1c4, #a98bff)",
    thumb: "/assets/thumbs/window-wash.png",
  },
  {
    slug: "welcome-to-webgame-arcades",
    title: "Welcome to Webgame Arcades",
    category: "Announcement",
    date: "2026-05-20",
    dateLabel: "May 20, 2026",
    summary: "Why we built a site full of free, install-free browser games — and what's coming next for the platform and the community.",
    thumbLabel: "SITE",
    thumbGradient: "linear-gradient(135deg, #8a7bd6, #4b4f9c)",
  },
];
